version = 1

[*]
c = 16384
temp = 0.7
top-p = 0.8
top-k = 20
min-p = 0.0
flash-attn = true
jinja = true
; n-gpu-layers = all
cache-type-k = q8_0
cache-type-v = q8_0

[Qwen3.5-35B-A3B]
model = /home/thomas/srv/llama-router/models/Qwen3.5-35B-A3B-GGUF/Qwen3.5-35B-A3B-UD-Q4_K_XL.gguf
load-on-startup = false

[Qwen3.5-35B-A3B-MTP]
model = /home/thomas/srv/llama-router/models/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
c = 131072
n-gpu-layers = auto
spec-type = draft-mtp
spec-draft-n-max = 2
load-on-startup = false

[Qwen3.5-27B]
model = /home/thomas/srv/llama-router/models/Qwen3.5-27B-GGUF/Qwen3.5-27B-UD-Q4_K_XL.gguf
load-on-startup = false

[Qwen3.5-35B-A3B-S]
model = /home/thomas/srv/llama-router/models/Qwen3.5-35B-A3B-GGUF/Qwen3.5-35B-A3B-UD-Q2_K_XL.gguf
load-on-startup = false

[Qwen3.5-9B]
model = /home/thomas/srv/llama-router/models/Qwen3.5-9B-GGUF/Qwen3.5-9B-UD-Q4_K_XL.gguf
load-on-startup = false
chat-template-kwargs = {"enable_thinking":false}

[Qwen3.5-9B-S]
model = /home/thomas/srv/llama-router/models/Qwen3.5-9B-GGUF/Qwen3.5-9B-UD-Q2_K_XL.gguf
load-on-startup = false
chat-template-kwargs = {"enable_thinking":false}

[Qwen3.5-9B-XSS]
model = /home/thomas/srv/llama-router/models/Qwen3.5-9B-GGUF/Qwen3.5-9B-UD-IQ2_XXS.gguf
load-on-startup = false
chat-template-kwargs = {"enable_thinking":false}

[Qwen3.5-4B]
model = /home/thomas/srv/llama-router/models/Qwen3.5-4B-GGUF/Qwen3.5-4B-UD-Q4_K_XL.gguf
load-on-startup = false
chat-template-kwargs = {"enable_thinking":false}

[Qwen3.5-4B-S]
model = /home/thomas/srv/llama-router/models/Qwen3.5-4B-GGUF/Qwen3.5-4B-UD-Q2_K_XL.gguf
load-on-startup = false
chat-template-kwargs = {"enable_thinking":false}

[Qwen3.5-2B]
model = /home/thomas/srv/llama-router/models/Qwen3.5-2B-GGUF/Qwen3.5-2B-UD-Q4_K_XL.gguf
load-on-startup = false
chat-template-kwargs = {"enable_thinking":false}

[Qwen3.5-2B-XL]
model = /home/thomas/srv/llama-router/models/Qwen3.5-2B-GGUF/Qwen3.5-2B-UD-Q8_K_XL.gguf
load-on-startup = false
chat-template-kwargs = {"enable_thinking":false}

[Qwen3.5-2B-VoiceInk]
model = /home/thomas/srv/llama-router/models/Qwen3.5-2B-voiceink_gguf/Qwen3.5-2B.Q4_K_M.gguf
load-on-startup = false
chat-template-kwargs = {"enable_thinking":false}

[LFM2.5-1.2B-Instruct]
model = /home/thomas/srv/llama-router/models/LFM2.5-1.2B-Instruct-GGUF/LFM2.5-1.2B-Instruct-UD-Q4_K_XL.gguf
c = 32768
temp = 0.1
top-p = 0.1
top-k = 50
repeat-penalty = 1.05
load-on-startup = false

[LFM2.5-1.2B-VoiceInk]
model = /home/thomas/srv/llama-router/models/LFM2.5-1.2B-VoiceInk_gguf/LFM2.5-1.2B-Instruct.Q4_K_M.gguf
c = 16384
temp = 0.1
top-p = 0.1
top-k = 50
repeat-penalty = 1.05
load-on-startup = false

[LFM2.5-1.2B-VoiceInk-Q8]
model = /home/thomas/srv/llama-router/models/LFM2.5-1.2B-VoiceInk_gguf/LFM2.5-1.2B-Instruct.Q8_0.gguf
c = 16384
temp = 0.1
top-p = 0.1
top-k = 50
repeat-penalty = 1.05
load-on-startup = false

[Gemma4-E2B]
model = /home/thomas/srv/llama-router/models/Gemma4-E2B-GGUF/gemma-4-E2B-it-UD-Q4_K_XL.gguf
temp = 1.0
top-p = 0.95
top-k = 64
load-on-startup = false
chat-template-kwargs = {"enable_thinking":false}

[Gemma4-E2B-Q8]
model = /home/thomas/srv/llama-router/models/Gemma4-E2B-Q8_0-GGUF/gemma-4-E2B-it-Q8_0.gguf
temp = 1.0
top-p = 0.95
top-k = 64
load-on-startup = false
chat-template-kwargs = {"enable_thinking":false}

[Gemma4-E4B]
model = /home/thomas/srv/llama-router/models/Gemma4-E4B-GGUF/gemma-4-E4B-it-UD-Q4_K_XL.gguf
temp = 1.0
top-p = 0.95
top-k = 64
load-on-startup = false

[Gemma4-E4B-Q8]
model = /home/thomas/srv/llama-router/models/Gemma4-E4B-Q8_0-GGUF/gemma-4-E4B-it-Q8_0.gguf
temp = 1.0
top-p = 0.95
top-k = 64
load-on-startup = false
